[package]
name = "my_microservice"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A modular microservice with async scaling"
repository = "https://github.com/yourusername/my_microservice"

[dependencies]
actix-web = "4.2"
actix-service = "1.1"
serde = { version = "1.3", features = ["derive"] }
uuid = "1.0"
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
